paths:
  mini_repo: ../ada-panda-mini
  tlgs: ../ada-panda-mini/reports/tlgs.parquet
  benchmarks: ../ada-panda-mini/reports/benchmarks.parquet
  figures: ../ada-panda-mini/reports/figures

report:
  title: "Clinical Pharmacology Summary – ADA Drug Interference & PandA Correction"
  sponsor: "Demo Biotech"
  product: "Monoclonal X"
  cutoff_recovery: 0.80
  required_tolerance_ugmL: 100
